import { Container } from "typescript-ioc";
import { AuthRepository } from "../../domain/contracts/auth-repository";
import { HttpAuthRepository } from "../repositories/auth-repository/http-auth-repository";
import { CategoriesRepository } from "../../domain/contracts/categories-repository";
import { HttpCategoriesRepository } from "../repositories/categories-repository/http-categories-repository";
import { CardRepository } from "../../domain/contracts/card-repository";
import { HttpCardRepository } from "../repositories/card-repository/http-card-repository";
import { TransactionRepository } from "../../domain/contracts/transaction-repository";
import { HttpTransactionRepository } from "../repositories/transaction-repository/http-transaction-repository";
import { BudgetRepository } from "../../domain/contracts/budget-repository";
import { HttpBudgetRepository } from "../repositories/budget-repository/http-budget-repository";
import { UsersRepository } from "../../domain/contracts/users-repository";
import { HttpUsersRepository } from "../repositories/users-repository/http-users-repository";
import { DashboardRepository } from "../../domain/contracts/dashboard-repository";
import { HttpDashboardRepository } from "../repositories/dashboard-repository/http-dashboard-repository";
import { HouseholdRepository } from "../../domain/contracts/household-repository";
import { HttpHouseholdRepository } from "../repositories/household-repository/http-household-repository";

Container.bind(AuthRepository).to(HttpAuthRepository);
Container.bind(HouseholdRepository).to(HttpHouseholdRepository);
Container.bind(CategoriesRepository).to(HttpCategoriesRepository);
Container.bind(CardRepository).to(HttpCardRepository);
Container.bind(TransactionRepository).to(HttpTransactionRepository);
Container.bind(BudgetRepository).to(HttpBudgetRepository);
Container.bind(UsersRepository).to(HttpUsersRepository);
Container.bind(DashboardRepository).to(HttpDashboardRepository);
